name: Python Flask Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Push to repository
    env:
      IMG_NAME: ${{ secrets.DOCKER_USERNAME }}/academic-engine-parse-docx
      TAGS: ${GITHUB_REF##*/}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Build and Push image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker image build -t ${{ env.IMG_NAME }}:${{ env.TAGS }}-v1 .
          docker push ${{ env.IMG_NAME }}:${{ env.TAGS }}-v1
  deploy:
    name: Deploy to production server
    needs: build
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ secrets.DOCKER_USERNAME }}/academic-engine-parse-docx
      TAGS: main
      CONTAINER_NAME: academic-engine-parse-docx-production-v1
    steps:
      - name: Executing deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.USER_SERVER }}
          password: ${{ secrets.PASSWORD_SERVER }}
          port: 22
          script: |
            docker pull ${{ env.IMG_NAME }}:${{ env.TAGS }}-v1
            docker rm -f ${{ env.CONTAINER_NAME }} || true
            docker run -d -p 8085:5000 --restart always --name ${{ env.CONTAINER_NAME }} ${{ env.IMG_NAME }}:${{ env.TAGS }}-v1